### ISSUE TITLE
Checklist from ProGit2 issue

### ISSUE THREAD

**Issue by HonkingGoose** [HonkingGoose/migration-test-progit2#4]
## GitHub will automate parts of the migration later this year:

Moving to the `main` branch as the default branch will be made easier for existing repositories, later this year: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

The changes made by GitHub will fix the following issues that moving on our own **now** would create:
- Open pull requests need to be re-targeted to the new branch
- Draft releases need to be re-targeted to the new branch
- Warning users who fetch/clone from our repository to use the new branch name, and help with migration by creating documentation.

So I would strongly suggest, that we wait until GitHub has fixed those issues, this will help with the load on the maintainers of this project, and increase the likelihood of a successful move.

We still need to manually fix certain things, whether we move manually now, or let GitHub automate parts of the process later.

## Preparation:

- [ ] Check with the translation projects if they are up for this move.
- [ ] Check with the git.scm project if they are up for this move, as they'll probably need to make some changes in their build steps to deliver our book on their website???
- [ ] Check the moving over checklist, figure out if more is needed?
- [ ] Go/no go decision.
- [ ] Decide on a "move over" date, and communicate it to the community via a pinned issue on GitHub.
- [ ] Pin the "move over" issue, so that it stays on the top of the "Issues" tab in GitHub.
- [ ] Write documentation on "How to change your branch from main to master as a contributor" and pin it with a Issue, and put it in the README.md.

## Moving over:
- [x] Merge pull-request #2  to:
* Change the [tag_on_master](https://github.com/progit/progit2/blob/master/script/tag_on_master) script to use `main` instead of `master`.
* Rename [tag_on_master](https://github.com/progit/progit2/blob/master/script/tag_on_master) script to tag_on_main.
* Ensure [travis.yml](https://github.com/progit/progit2/blob/master/.travis.yml) uses the renamed tag_on_main script.
* Ensure [travis.yml](https://github.com/progit/progit2/blob/master/.travis.yml) uses the `main` branch for its tests.
* Change the reference to `master` to `main` in [atlas.json](https://github.com/progit/progit2/blob/master/atlas.json)
* Change a link in the translation documentation.
* Change a link in the bug report template.
- [x] Create a `main` branch, and push it to the repository.
- [x] Copy the branch protection policies that are used on `master` to the new `main` branch.
- [x] Change the default branch from `master` to `main` on the repository settings page.
- [x] Re-target open pull-requests, this can be done manually by the pull owner, by going to the pull-request, and clicking on *edit*, and select the `main` branch as target for the pull. _Or we can wait until GitHub has automated this._
- [x] Dependabot will re-target its pull requests to the main branch automatically.
- [x] Finally after ensuring everything still works, delete the `master` branch on the remote.

## Benefits/drawbacks of proposal:

Benefits:
- The project will be more inclusive to people who are bothered by the `master` `slave` connotation.
- Give a good example on how to move a project over, so that other projects know the move can be done.

Drawbacks:
- There are currently 1600 forks/clones at least of this repository, _including the translation projects_, each of those will have to do some work after the move.
- The maintainers of the ProGit2 project will be quite busy with merging/closing pull-requests prior to the move. _This will not be necessary if we wait until GitHub makes things easier later this year..._
- There's a chance that we miss changing/updating something prior to the move, and we break something.

## Related issues:
#1462

## Further info: 
More info and guidance from GitHub on moving a repo from `master` to `main` can be found at [GitHub's official renaming repo](https://github.com/github/renaming).

---

**Edits:**

I've removed a previously listed drawback (breaking the old links to files on `master`, as it's fixed by GitHub already...
> Links to deleted branches now redirect to the default branch

Source: https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/
